### ISSUE TITLE
{General question about opening issues here vs upstream.}

### ISSUE THREAD

**Issue by Aninti** [kutzlect/io.github.thaunknown.miru#6]
When should you report bugs or ask for features here vs upstream?

**Comment by ecficies** [comment]
You should definitely ask for features on upstream. This repo only deals with the Flatpak and is quite obsolete as it's already available on Flathub (there's a repo for the manifest which has an issue tracker as well).
Bugs should be reported upstream if you made sure you can replicate them on other packaging formats. Otherwise, use the manifest's repo on Flathub.
